### ISSUE TITLE
Exclude TS type from circular detection

### ISSUE THREAD

**Issue by ooga** [antoine-coulon/skott#100]
I think Typescript types should be excluded from circular dependencies detection

All type declarations will be deleted when compiling ts file, so there will be no negative effect in final code

**Comment by antoine-coulon** [comment]
Opened an issue for the CLI here #101

**Comment by antoine-coulon** [comment]
Just created another issue #102 for skott to support `import type { X }` as well

**Comment by antoine-coulon** [comment]
Fixed in `0.29.1` you can now use again `skott --no-trackTypeOnlyDependencies` so that `import type { X }` are discarded from the analysis. There is an on going PR #105 that will allow to do the same + to discard also `import { type X }`, that will be landed in `0.30.0` tomorrow.

**Comment by antoine-coulon** [comment]
`0.30.0` just landed, `import { type X }` is now supported and will be discarded from the analysis when ignoring type-level imports as expected.

I'm now closing this issue as skott's philosophy is to track by default all circular dependencies, whether they are harmful or not at runtime. The choice can be then made by the user, using configuration, to discard some nodes involved in the cycles by targeting runtime imports only.

To enforce type-level import consistency (that is using `import type` or `import { type }`), allowing skott to totally discard them, linting rules can be applied `'@typescript-eslint/consistent-type-imports': 'error'`.
