### ISSUE TITLE
Refresh application 

### ISSUE THREAD

**Issue by austinm911** [antoine-coulon/skott#126]
## Summary
Would be nice to have a way to refresh the application or set a --watch flag, instead of having to restart the ap.

**Comment by antoine-coulon** [comment]
@austinm911 glad to know it helps you resolving circular dependencies problem. Note that this is not related to that issue, but I'm also planning to improve and add a lot more features around circular dependencies to help work with them :) 

Going back to the initial issue, I can see how fast it can become harmful for the DX to have to restart everything when resolving circular dependencies or even when updating files. I'll think of a solution whether it's through auto-refresh or a manual action button and I'll let you know in that thread.

**Comment by antoine-coulon** [comment]
Hello @austinm911, 

I have been working on a universal watch mode lately, you can see the changes in the opened PR. 

For the first version, watch mode will be available for all types of display modes (webapp, file-tree, graph and raw) and it will work transparently and automatically under the hood (no user action needed). For the webapp, I'm implementing Server-Sent Events to provide real time notifications and automatically update the graph rendering.

I will keep you updated :)

**Comment by antoine-coulon** [comment]
Hello @austinm911, a `--watch` flag was introduced in `0.32.0` I just published. When used in combination with `--displayMode=webapp`, it will automatically refresh the graph using real-time events (no page reload). Let me know how it goes for you!
