### ISSUE TITLE
fs-tree-structure is using a lodash.set that has high severity vulnerability!

### ISSUE THREAD

**Issue by pedrolamas** [antoine-coulon/skott#137]
## Summary

I've noticed the fs-tree-structure is using lodash.set which is 7 years old(!) and has been known to have a high severity vulnerability: https://github.com/advisories/GHSA-p6mc-m468-83gw

## Reproduction steps

- Create a new empty folder
- Inside the new folder, run `npm i skott` (this is the single package we need to install)
- Run `npm audit` and observe results

![image](https://github.com/antoine-coulon/skott/assets/85504/b0cd9aca-246b-45ac-99c1-7890f206b266)

**Expected result:** 

Audit should not report any known vulnerabilities.

**Actual result:** 

Audit reports known vulnerability.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `skott` installed version? | 0.32.0 |
| Operating system? | Ubuntu (WSL2 in Windows 11) |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v20.9.0 |

**Comment by antoine-coulon** [comment]
Hello @pedrolamas, thanks for the heads up and the landed fix!
