### ISSUE TITLE
Find unused external dependencies

### ISSUE THREAD

**Issue by ild0tt0re** [antoine-coulon/skott#14]
I would like to find unused npm packages

**Comment by antoine-coulon** [comment]
Hello @ild0tt0re, 

Thanks for opening a feature request once again!

By "unused npm packages" do you mean packages that are present in the node_modules but not imported anywhere (ghost node_modules) or you were thinking about packages that are imported in the source code but not used in the files they are imported from?

**Comment by ild0tt0re** [comment]
> Hello @ild0tt0re, 
> 
> Thanks for opening a feature request once again!
> 
> By "unused npm packages" do you mean packages that are present in the node_modules but not imported anywhere (ghost node_modules) or you were thinking about packages that are imported in the source code but not used in the files they are imported from?

I mean the ghost node_modules

**Comment by antoine-coulon** [comment]
I think it would be useful yeah, but mainly for production dependencies, because the use of devDependencies would be too tedious to track (bundling or linting tools use is not visible from within the files themselves).

So for all production dependencies found in all the package.json files encountered starting from the directory from which the command "skott" was started, Skott will compare the ones used vs the ones not used.

Seems good? @ild0tt0re

**Comment by ild0tt0re** [comment]
> I think it would be useful yeah, but mainly for production dependencies, because the use of devDependencies would be too tedious to track (bundling or linting tools use is not visible from within the files themselves).
> 
> So for all production dependencies found in all the package.json files encountered starting from the directory from which the command "skott" was started, Skott will compare the ones used vs the ones not used.
> 
> Seems good? @ild0tt0re

Yeah seems a good start!

**Comment by antoine-coulon** [comment]
A **v0.13.0** was just published including the first version of the feature.

It adds a new `--showUnusedDependencies` flag which when combined with `--trackThirdPartyDependencies` will report all unused third-party dependencies.

Note that another flag `--manifest` can be used to provide a path to any **package.json**:

`skott my-app/src/index.ts --manifest=my-app/package.json --trackThirdPartyDependencies --showUnusedDependencies`

**Comment by antoine-coulon** [comment]
Closing this as it's probably good enough on this topic for the V1 to be landed.
