### ISSUE TITLE
Feature request: highlight all dependencies of a file

### ISSUE THREAD

**Issue by MengLinMaker** [antoine-coulon/skott#179]
## Summary

Using this tool to help port libraries from one framework to another.

The ability to highlight all imports, import of imports... essentially all dependencies would show which files should be ported

## Details

Could be enabled by toggle in the `Dependencies configuration` tab.
Highlight could be in green - or any color.

## Standard questions

Would you consider contributing a PR? Yes

**Comment by antoine-coulon** [comment]
Hey @MengLinMaker, thanks for opening an issue!

I'm glad skott helps you porting libraries, this is also a use case I found useful for it!

Are you talking about third-party dependencies? Let's say you want to port React to Angular, you would want to highlight all file nodes where there is a `import React from "react"` for instance? I guess we could have a way to search for any kind of import identifier, whether a third-party module or a local module

Also if you're willing to contribute, please feel free to open up a draft PR I can help you get it done :)
