### ISSUE TITLE
Add support for `npx skott`

### ISSUE THREAD

**Issue by fregante** [antoine-coulon/skott#19]
The CLI doesn't seem to work when run via npx: 

<img width="696" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/209500020-ca0faf4d-7ac4-4676-a996-dc0ec75845f8.png">

If it's available globally, then `npx` will also work, so make sure you uninstall the global version before attempting this.

**Comment by antoine-coulon** [comment]
Hello @fregante 

Thanks again for reporting an issue.

From my understanding it is only related to the "webapp" display mode so I'll investigate why it happens

**Comment by antoine-coulon** [comment]
Good evening @fregante,

Could you please tell me what version of Node and npm you're using to face that issue?
I can't reproduce the behavior mentioned above using **Node 16.14.0** and **npm 8.3.1**.

Thanks

**Comment by fregante** [comment]
I cleared the cache, it still happens:

```sh

❯ rm -rf ~/.npm/_npx

❯ node --version
v18.10.0

❯ npm --version
8.19.2

❯ npx skott src/pageScript/pageScript.ts --trackBuiltinDependencies --trackThirdPartyDependencies --displayMode=file-tree --tsconfig tsconfig.djson
Need to install the following packages:
  skott@0.12.3
Ok to proceed? (y) y
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "^0.2.0 timsort" of package "^0.2.0 timsort@^0.3.0 uuid@^3.4.0": name can only contain URL-friendly characters.
```

**Comment by fregante** [comment]
And I noticed that even with `skott` installed, #20 still happens when I run it via `npx`
<img width="290" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/209770581-869ab4bb-0b7c-403a-b78b-df202e8f418c.png">


While it works fine when calling the global version directly:

<img width="446" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/209770684-00bfcc2e-01c0-4d9d-8447-85f00c6a6452.png">





. I assume this is because `npx` changes some ENVs in the process, but apps should work in both cases. This is probably a resolution issue based on CWD, etc

**Comment by antoine-coulon** [comment]
@fregante thank you all this detailed information!

I'll keep investigating and I'll let you know about the updates

**Comment by antoine-coulon** [comment]
Good morning @fregante,

I just pushed a `0.12.6` version which seems to work with **npx**, just tested now on your _pixiebrix_ project, from what I could see `npx skott src/pageScript/pageScript.ts` and `skott src/pageScript/pageScript.ts` seem to behave the same way now.

I'll let you confirm it by testing on your project, I let the issue open for now

**Comment by antoine-coulon** [comment]
My pleasure! I think you did (for the last example) but everything else you reported was right so thanks for doing it 😄
