### ISSUE TITLE
FeatureRequest | Typescript support

### ISSUE THREAD

**Issue by ild0tt0re** [antoine-coulon/skott#2]
# Feature Request

Will skott support **typescript** projects?

Our use case is an **Nx** monorepo with Nextjs as the main app with several **react** libraries.
Thanks for this interesting library!

**Comment by antoine-coulon** [comment]
Hello @ild0tt0re, all the pleasure is mine, thank you for your interest in skott!

> # Feature Request
> Will skott support **typescript** projects?
> 

Yes, skott **will support TypeScript** for sure! Lately, I've been stabilizing features around the CLI but I had in mind to support TypeScript (which I mainly use on all my projects). The fact that you're suggesting that feature is just encouraging me to do it even more quickly :) I'll also need to deal with JSX/TSX parsing (as you mentioned React), so I'll embed that at the same time ✍️ 

> Our use case is an **Nx** monorepo with Nextjs as the main app with several **react** libraries. Thanks for this interesting library!

Would you find interesting to be able to run _skott_ directly on the whole monorepo itself, taking into account that they mostly already implement [their own graph representation tool](https://nx.dev/nx/dep-graph)?

**Comment by ild0tt0re** [comment]
> Hello @ild0tt0re, all the pleasure is mine, thank you for your interest in skott!
> 
> > # Feature Request
> > Will skott support **typescript** projects?
> > 
> 
> Yes, skott **will support TypeScript** for sure! Lately, I've been stabilizing features around the CLI but I had in mind to support TypeScript (which I mainly use on all my projects). The fact that you're suggesting that feature is just encouraging me to do it even more quickly :) I'll also need to deal with JSX/TSX parsing (as you mentioned React), so I'll embed that at the same time ✍️ 
> 
> > Our use case is an **Nx** monorepo with Nextjs as the main app with several **react** libraries. Thanks for this interesting library!
> 
> Would you find interesting to be able to run _skott_ directly on the whole monorepo itself, taking into account that they mostly already implement [their own graph representation tool](https://nx.dev/nx/dep-graph)?
> 

Hi @antoine-coulon! 

Yes, I find it interesting because they are two tools with different purposes. 

On the Nx graph there are information relating to the projects that are part of the monorepo and the third-parties dependencies (the main purpose is the calculation of the affected projects).  

Skott would allow me to go into detail by viewing also the modules / files of a project from which you could extract data such as size, etc .. 

I would have some nice API/features built-in 
- number of times a module is used starting from a root module/subtree (ie: i want known in which page a component is used and how many times,... )
- I would known how the module is used and where in different way (imported with require/import, Lazy loaded,... ) 
- I would known how many duplicated modules are in the codebase
- can i know how many times a react component has been used whit a Specific prop? (useful for code refactoring)

These are some ideas that i have at the moment.

**Comment by antoine-coulon** [comment]
By the way @ild0tt0re, I just merged the PR #3 which allows **skott** to process TypeScript projects. I'm opening another PR to support JSX/TSX

**Comment by antoine-coulon** [comment]
Closing this discussion as **TypeScript** and **JSX** support were both added in [v0.6.0](https://github.com/antoine-coulon/skott/releases/tag/v0.6.0).

The only missing part that might interest you @ild0tt0re as you are using Next.js is mentioned here #5 in its own dedicated issue.

**Comment by ild0tt0re** [comment]
Thanks @antoine-coulon!

- for `starting from a root module/subtree` I mean starting from an entrypoint that is different from the root of the app

- for `duplicated module` i mean the possibility to discover which modules are a copy/paste of others
