### ISSUE TITLE
imports misclassified as third party dependencies

### ISSUE THREAD

**Issue by axelchauvin** [antoine-coulon/skott#30]
Hi!

It seems that if I have a relative path in my import such as: 
`import myObj from './other/folder'`
it gets correctly tracked as a dependency but if I have a absolute path import that relies on the tsconfig "baseUrl" such as:
`import myObj from 'absolute/path/folder'`
it gets classified as a third party dependency. 

I ran the command using the cli and have specified my tsconfig file using --tsconfig

**Comment by antoine-coulon** [comment]
Hello @axelchauvin, thanks for reporting that issue!

Just to be sure when fixing the thing, can you either paste your `tsconfig.json` here or confirm that you're using `baseUrl` on it's own, without `paths`, please?

I presume that you're using it like:

**tsconfig.json**
```json
{
   "baseUrl": "./"
}
```

If you're setting `baseUrl` alone, it's in fact something that is not supported yet (even if it's a valid way of doing it) so I'll push a fix asap

**Comment by axelchauvin** [comment]
yep, basically 

```
{
   "compilerOptions": {
        "baseUrl":"./"
    }
}

**Comment by antoine-coulon** [comment]
Alright thanks for confirming that, I'm already working on a fix. Should be done and released today

**Comment by antoine-coulon** [comment]
The PR was merged and I just released the `0.20.1` version that should embed that fix. Could you please try with that last version and tell me if that fixes your problem? Thanks

**Comment by antoine-coulon** [comment]
Hello @axelchauvin were you able to test the fix on your side?

**Comment by antoine-coulon** [comment]
Closing that issue due to inactivity and because the latest versions should fix the issue. Feel free to re-open it if ever you still encounter the same problem.
