### ISSUE TITLE
Add support for getDeepChildren

### ISSUE THREAD

**Issue by alyahmedaly** [antoine-coulon/skott#56]
Hello, I would love if you can support `getDeepChildren` or expose the graph in the api so I can use [digraph-js](https://github.com/antoine-coulon/digraph-js)

**Comment by alyahmedaly** [comment]
or a way to use the digraph api from the returned graph (maybe it's already supported)

**Comment by antoine-coulon** [comment]
Hello @alyahmedaly, the graph emitted by skott is structurally compliant with the one that can be provided to `digraph-js` (skott does not modify its inner shape)

That way you could do : 

```js
import skott from "skott";
import { DiGraph } from "digraph-js";

const { getStructure } = await skott();
const { graph } = await getStructure();
const digraph = DiGraph.fromRaw(graph);

for (const nodeId of Object.keys(graph)) {
  const childrenNodes = [...digraph.getDeepChildren(nodeId)];
  console.log(`${nodeId} -> ${childrenNodes}`);
}
```

Even though it's possible as is, it's not really convenient as the underlying graph instance (allowing to use methods such as `getDeepChildren`) has to be constructed twice. Need to think about that a little bit given that returning a raw graph from skott is not really helpful in itself, I believe the ones like you trying to use that graph would rather use pre-defined methods allowing to traverse the graph and search through it, right?

**Comment by alyahmedaly** [comment]
@antoine-coulon Thanks for sharing
I think having the graph is valuable, but indeed adding some apis to traverse it makes sense as well
I think about it like typescript compiler api you can parse source files as AST but you still have all the traverse methods available to be used with AST nodes https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API

**Comment by antoine-coulon** [comment]
@alyahmedaly Yeah that's why I basically meant by `use pre-defined methods allowing to traverse the graph and search through it`, indeed I could expose both, a static version of the graph (0 cost) and some methods that facilitate node traversal and node queries, essentially what `digraph-js` can do but might be slightly oriented towards specific use cases that we can have on a filesystem project (cause `digraph-js` is meant to be agnostic so I'd rather let skott deal with that specific jargon)

**Comment by antoine-coulon** [comment]
A first version of a little traversal API was just merged on digraph-js's side.

I'll implement that on the skott side in the following days.

**Comment by antoine-coulon** [comment]
Hello @alyahmedal  

The very first version of the traversal API has been merged, let me know if that covers your primary use cases. 

I'd be happy to keep extending it as the skott's goal is mainly to facilitate everything related to the use of the underlying graph generated
