### ISSUE TITLE
Add option to support resolving test files

### ISSUE THREAD

**Issue by alyahmedaly** [antoine-coulon/skott#57]
Looks like test files are ignored by default it would be great if I can control that using the API

**Comment by antoine-coulon** [comment]
Hey @alyahmedaly, glad to see you again there!

It's true that the current behaviour is not really flexible and is opinionated, but great news I'm currently working on https://github.com/antoine-coulon/skott/issues/34 that will be merged tomorrow. Adding that ignorePattern will allow me to get rid of the default ignored directories and files by default meaning that tests files (and every other supported files) will be included in the analysis in case they are not explicitly ignored by the glob pattern.

**Comment by antoine-coulon** [comment]
Hello @alyahmedaly, test files are now by default analyzed. If you still wish to filter out some files, you are now able to use `ignorePattern` option, either from

cli:
`skott --ignorePattern="test/**/*"`

or api:
```ts
skott({ ignorePattern: "test/**/*" })
```

let me know how this goes for you even if I'm closing this issue as it should be now resolved :)
