### ISSUE TITLE
Doesn't support "baseUrl" in tsconfig.json when tsconfig.json is in a different folder

### ISSUE THREAD

**Issue by grumd** [antoine-coulon/skott#74]
Codesandbox: https://codesandbox.io/p/sandbox/dazzling-smoke-njhyww

I'm using `"baseUrl": "src"` so that I can resolve absolute imports in TS relative to baseUrl.

import `from 'bar/bar'` should resolve to `./src/bar/bar`

Skott doesn't resolve the import to `bar.ts`:

![image](https://github.com/antoine-coulon/skott/assets/5869818/e76b7944-d9e0-49c4-84d0-a204f0eee682)

Even though it's imported from `foo.ts` and Typescript works correctly with this setup.

**Comment by grumd** [comment]
Inveestigated some more:

It works correctly when tsconfig.json is in the same folder as my working dir when running Skott.

But it doesn't work when tsconfig is in a different folder.

**`baseUrl` should be resolved relative to `tsconfig.json`**

**Comment by grumd** [comment]
1. With this config:
![image](https://github.com/antoine-coulon/skott/assets/5869818/4e9e9ffc-ec1a-4d9d-a501-607f32fee7fb)

![image](https://github.com/antoine-coulon/skott/assets/5869818/8d8f9dc0-a98a-484f-bfb5-15b5ceaaabd0)

2. With a subfolder:
![image](https://github.com/antoine-coulon/skott/assets/5869818/7a563084-8d71-41ff-9883-c48dcd7369e8)
![image](https://github.com/antoine-coulon/skott/assets/5869818/d8423b0f-a6a8-44a0-9b5e-44f7932786aa)

**Comment by antoine-coulon** [comment]
Hey @grumd, nice catch, thanks for opening that issue with that complete repro.

I just checked and I believe your analysis is on point, paths only relying on "baseUrl" won't be resolved correctly when the tsconfig is not located in the working directory where the analysis was started from.

I'm currently on vacations so pushing an immediate fix (as I love to do) will be hard for me, but I started a little bit to think about it and implement a fix for it, it will most likely take into account the location of the provided tsconfig file to resolve these absolute module imports to reproduce the same behaviour as if the analysis was started from the current working directory. 

Please also note that it's a specific case where only "baseUrl" is provided without plain path aliases (via "paths" property).

I'll keep you updated here in that issue. If you ever encounter other  issues feel free to share them as well :)

**Comment by antoine-coulon** [comment]
This was auto-closed, @grumd I'll let please you confirm that this works in 0.28.2 before closing the issue

**Comment by grumd** [comment]
Just in case retested it and seems to work correctly now! Thanks!

**Comment by antoine-coulon** [comment]
Thanks for confirming that @grumd but also for raising the issue!
