### ISSUE TITLE
Add `usage` point in README.md

### ISSUE THREAD

**Issue by mnik01** [antoine-coulon/skott#86]
Please provide better documentation for usage.

It should tell how to install and use the tool.
Because now it's not clear for me.

**Comment by antoine-coulon** [comment]
Hello, there is a **Documentation** section in the root monorepo README.md that binds to https://github.com/antoine-coulon/skott/blob/main/packages/skott/README.md. What else do you suggest? I can try to make it clearer that the root README.md is just the presentation, not the documentation of the tool itself

**Comment by antoine-coulon** [comment]
<img width="901" src="https://github.com/antoine-coulon/skott/assets/43391199/426ddcb9-83ff-46cd-8671-d6bb3290ab22">

Here is the documentation section I'm referring to

**Comment by antoine-coulon** [comment]
Also, the "usage" documentation is exposed in npm https://www.npmjs.com/package/skott

**Comment by mnik01** [comment]
Sorry.
My bad, didn't notice it at first

Thank you for answering

**Comment by antoine-coulon** [comment]
All good @mnik01 thanks to you for opening that issue!

**Comment by antoine-coulon** [comment]
Hello @mnik01, just updated the README.md as you suggested. Hope that's better now.

Cheers
